# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#loginPage{\n"
"    background-image: url(:/images/images/background.jpg);\n"
"}\n"
"\n"
"#formLoginWidget{ \n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"#errorlabel {\n"
"    color: red;\n"
"}\n"
"\n"
"#input_password {\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"#loginBtn {\n"
"    border-radius: 7px;\n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"}\n"
"\n"
"#loginBtn:hover {\n"
"    background-color: rgba(255, 255, 255, 0.6);\n"
"}\n"
"\n"
"#loginBtn:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.8);\n"
"}\n"
"\n"
"#welcomelabel {    \n"
"    color: rgba(255, 255, 255, 0.9)\n"
"}\n"
"\n"
"#stackedWidget_2 {\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"#viewWidget {\n"
"    background-color: rgb(245, 245, 245) \n"
"}\n"
"\n"
"#inputs_sideWidget {\n"
"    background-color: rgb(245, 245, 245) \n"
"}\n"
"\n"
"#email_input, #sitename_input, #username_input, #password_input {\n"
"    border-radius: 7px;\n"
"    border: 1px solid rgb(218, 218, 218);\n"
"}\n"
"\n"
"#deleteBtn {\n"
"    background-color: red;\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    border: 0.5px solid black;\n"
"}\n"
"\n"
"#deleteBtn:hover {\n"
"    background-color: rgb(236, 0, 0);\n"
"}\n"
"\n"
"#deleteBtn:pressed {\n"
"    background-color: rgb(225, 0, 0);\n"
"}\n"
"\n"
"#addBtn, #updateBtn {\n"
"    border-radius: 7px;\n"
"    border: 0.5px solid black;\n"
"}\n"
"\n"
"#addBtn:hover, #updateBtn:hover {\n"
"    background-color: rgb(245, 245, 245);\n"
"}\n"
"#addBtn:pressed, #updateBtn:pressed {\n"
"    background-color: rgb(231, 231, 231)\n"
"}\n"
"\n"
"#tableInfo {\n"
"    border:none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loginPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLoginWidget = QtWidgets.QWidget(self.loginPage)
        self.formLoginWidget.setMinimumSize(QtCore.QSize(400, 400))
        self.formLoginWidget.setStyleSheet("")
        self.formLoginWidget.setObjectName("formLoginWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.formLoginWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.formLoginWidget)
        self.stackedWidget_2.setStyleSheet("")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.input_password = QtWidgets.QLineEdit(self.login_page)
        self.input_password.setGeometry(QtCore.QRect(110, 140, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_password.setFont(font)
        self.input_password.setStyleSheet("")
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.errorlabel = QtWidgets.QLabel(self.login_page)
        self.errorlabel.setGeometry(QtCore.QRect(110, 90, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.errorlabel.setFont(font)
        self.errorlabel.setObjectName("errorlabel")
        self.loginBtn = QtWidgets.QPushButton(self.login_page)
        self.loginBtn.setGeometry(QtCore.QRect(110, 190, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loginBtn.setFont(font)
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginBtn.setObjectName("loginBtn")
        self.welcomelabel = QtWidgets.QLabel(self.login_page)
        self.welcomelabel.setGeometry(QtCore.QRect(110, 40, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.welcomelabel.setFont(font)
        self.welcomelabel.setObjectName("welcomelabel")
        self.stackedWidget_2.addWidget(self.login_page)
        self.horizontalLayout.addWidget(self.stackedWidget_2)
        self.verticalLayout_2.addWidget(self.formLoginWidget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.loginPage)
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.homePage)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewWidget = QtWidgets.QWidget(self.homePage)
        self.viewWidget.setObjectName("viewWidget")
        self.tableInfo = QtWidgets.QTableWidget(self.viewWidget)
        self.tableInfo.setGeometry(QtCore.QRect(0, 0, 581, 581))
        self.tableInfo.setStyleSheet("")
        self.tableInfo.setObjectName("tableInfo")
        self.tableInfo.setColumnCount(4)
        self.tableInfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInfo.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_2.addWidget(self.viewWidget)
        self.inputs_sideWidget = QtWidgets.QWidget(self.homePage)
        self.inputs_sideWidget.setMaximumSize(QtCore.QSize(220, 16777215))
        self.inputs_sideWidget.setObjectName("inputs_sideWidget")
        self.sitename_input = QtWidgets.QLineEdit(self.inputs_sideWidget)
        self.sitename_input.setGeometry(QtCore.QRect(32, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sitename_input.setFont(font)
        self.sitename_input.setObjectName("sitename_input")
        self.username_input = QtWidgets.QLineEdit(self.inputs_sideWidget)
        self.username_input.setGeometry(QtCore.QRect(32, 140, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_input.setFont(font)
        self.username_input.setObjectName("username_input")
        self.password_input = QtWidgets.QLineEdit(self.inputs_sideWidget)
        self.password_input.setGeometry(QtCore.QRect(32, 180, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_input.setFont(font)
        self.password_input.setObjectName("password_input")
        self.email_input = QtWidgets.QLineEdit(self.inputs_sideWidget)
        self.email_input.setGeometry(QtCore.QRect(32, 220, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_input.setFont(font)
        self.email_input.setObjectName("email_input")
        self.addBtn = QtWidgets.QPushButton(self.inputs_sideWidget)
        self.addBtn.setGeometry(QtCore.QRect(32, 270, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.updateBtn = QtWidgets.QPushButton(self.inputs_sideWidget)
        self.updateBtn.setGeometry(QtCore.QRect(32, 310, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.updateBtn.setFont(font)
        self.updateBtn.setObjectName("updateBtn")
        self.deleteBtn = QtWidgets.QPushButton(self.inputs_sideWidget)
        self.deleteBtn.setGeometry(QtCore.QRect(32, 430, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setObjectName("deleteBtn")
        self.horizontalLayout_2.addWidget(self.inputs_sideWidget)
        self.stackedWidget.addWidget(self.homePage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuabout = QtWidgets.QMenu(self.menubar)
        self.menuabout.setObjectName("menuabout")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_developer = QtWidgets.QAction(MainWindow)
        self.actionAbout_developer.setObjectName("actionAbout_developer")
        self.menuabout.addAction(self.actionAbout)
        self.menuabout.addAction(self.actionAbout_developer)
        self.menubar.addAction(self.menuabout.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Manager"))
        self.input_password.setPlaceholderText(_translate("MainWindow", "Enter the password"))
        self.errorlabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.loginBtn.setText(_translate("MainWindow", "Login"))
        self.welcomelabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Welcome back</p></body></html>"))
        item = self.tableInfo.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Site name"))
        item = self.tableInfo.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableInfo.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableInfo.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        self.sitename_input.setPlaceholderText(_translate("MainWindow", "Site name"))
        self.username_input.setPlaceholderText(_translate("MainWindow", "Username"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.email_input.setPlaceholderText(_translate("MainWindow", "Email"))
        self.addBtn.setText(_translate("MainWindow", "Add"))
        self.updateBtn.setText(_translate("MainWindow", "Update"))
        self.deleteBtn.setText(_translate("MainWindow", "Delete"))
        self.menuabout.setTitle(_translate("MainWindow", "help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout_developer.setText(_translate("MainWindow", "About developer"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
